services:
  receiver:
    build:
      context: ./app_receiver
      dockerfile: Dockerfile
    image: streaming-arm/python:3.13-slim
    environment:
      ALPACA_API_KEY: ${ALPACA_API_KEY}
      ALPACA_API_SECRET: ${ALPACA_API_SECRET}
      ALPACA_URI: ${ALPACA_URI}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      KINESIS_STREAM_ARN: ${KINESIS_STREAM_ARN}
      STREAM_NAME: ${STREAM_NAME}
    networks:
      - shared-network

networks:
  shared-network:
    external: true